name: diet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  provider: ^6.1.2


  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/login_image.png
